export const choices = {
  framework: [['flutter', 'Flutter'], ['rn', 'React Native CLI'], ['expo', 'Expo development build'], ['native', 'Kotlin / Swift SDK — in development']],
  platform: [['both', 'Android + iOS'], ['android', 'Android'], ['ios', 'iOS']],
  ui: [['supplied', 'Callx overlay + mini-call'], ['custom', 'My Dart / TypeScript screens'], ['native', 'Configured native call screen — planned']],
  media: [['livekit', 'LiveKit audio/video'], ['own', 'My media engine'], ['twilio', 'Twilio — planned'], ['zoom', 'Zoom — planned'], ['agora', 'Agora — planned']],
  backend: [['own', 'My backend'], ['local', 'Local demo tools'], ['hosted', 'Callx hosted service — future']],
  migration: [['new', 'New integration'], ['callkeep', 'Migrate from CallKeep'], ['flutter-callkit', 'Migrate from flutter_callkit_incoming']],
} as const;
export type Selection = {[K in keyof typeof choices]: typeof choices[K][number][0]};
export const defaults: Selection = {framework: 'flutter', platform: 'both', ui: 'supplied', media: 'livekit', backend: 'own', migration: 'new'};
export type Step = {title: string; detail: string; check: string; link: string};
export function buildPlan(s: Selection) {
  const blockers: string[] = [];
  if (s.framework === 'native') blockers.push('Standalone Kotlin/Swift SDKs are in development, not published. Local packaging checks exist; native host APIs currently ship inside Flutter/RN packages.');
  if (s.ui === 'native') blockers.push('A unified native call-screen configuration from Dart/TypeScript is planned. Android presenter hooks exist in Kotlin; iOS incoming presentation uses CallKit.');
  if (!['livekit', 'own'].includes(s.media)) blockers.push(`The ${s.media} Callx adapter is planned and has no installable package.`);
  if (s.backend === 'hosted') blockers.push('The Callx hosted backend is a future direction, not an available service.');
  if (s.migration === 'callkeep' && s.framework !== 'rn' && s.framework !== 'expo') blockers.push('The CallKeep migration journey targets React Native/Expo. Choose that framework or start a new integration.');
  if (s.migration === 'flutter-callkit' && s.framework !== 'flutter') blockers.push('The flutter_callkit_incoming migration journey targets Flutter.');
  const integration = s.framework === 'flutter' ? '/guide/flutter' : s.framework === 'expo' ? '/guide/expo' : '/guide/react-native';
  const migration = s.migration === 'callkeep' ? '/guides/migrate-callkeep' : '/guides/migrate-flutter-callkit-incoming';
  const install = s.framework === 'flutter' ? 'flutter pub add callx' : s.framework === 'expo' ? 'npx expo install @bear-block/callx' : 'npm install @bear-block/callx';
  const adapter = s.framework === 'flutter' ? 'flutter pub add callx_livekit' : s.framework === 'expo' ? 'npx expo install @bear-block/callx-livekit' : 'npm install @bear-block/callx-livekit';
  const steps: Step[] = [];
  if (s.migration !== 'new') steps.push({title: 'Audit the existing integration', detail: 'Map call IDs, push handlers, system presenters, media joins and backend callbacks before removing the old implementation.', check: 'Each app installation has exactly one call stack selected; existing clients retain their payload format.', link: migration});
  steps.push({title: 'Install and bootstrap', detail: 'Install the package, apply native configuration and rebuild the app. Expo requires a development build; Expo Go cannot load the native SDK.', check: 'Native bootstrap and framework setup complete without errors.', link: integration});
  steps.push({title: 'Prepare push and permissions', detail: s.platform === 'android' ? 'Configure Firebase/FCM, notification and microphone permissions; verify nativeCalling capability.' : s.platform === 'ios' ? 'Configure APNs VoIP, signing, Push Notifications and audio/VoIP background modes. Use a real iPhone for pushes.' : 'Configure Firebase/FCM on Android and APNs VoIP/signing on iOS. Request microphone and notification permissions as applicable.', check: 'The device reports its platform push token. Camera permission is requested before publishing video.', link: s.platform === 'ios' ? '/platforms/ios' : '/platforms/android'});
  steps.push({title: s.backend === 'local' ? 'Run local trial signaling' : 'Connect your backend', detail: s.backend === 'local' ? (s.media === 'livekit' ? 'Use the example call console and local LiveKit server. Real pushes still need your Firebase/APNs credentials; preview mode alone does not prove push delivery.' : 'Use the call console for test signaling and configure your own media engine. Real pushes still need your Firebase/APNs credentials; the tools do not implement your engine.') : 'Register installation tokens with the signed-in account. Create a call ID, send the invitation and relay answer/end signals to the native ingress.', check: 'The intended device rings once; duplicate or expired invitations do not produce a second incoming screen.', link: s.backend === 'local' ? '/guides/testing' : '/backend/'});
  steps.push({title: s.media === 'livekit' ? 'Add native LiveKit media' : 'Integrate your media engine', detail: s.media === 'livekit' ? 'Install the adapter, configure its native discovery and provide an authenticated media-token endpoint. Callx starts media on native acceptance.' : 'Implement native media lifecycle hooks and report connection/interruption to the core. A runtime-only join cannot cover answers before Dart/JS starts.', check: 'Both participants join the same call room using distinct identities. The call becomes active when media connects.', link: s.media === 'livekit' ? '/guide/livekit' : '/guides/own-media'});
  steps.push({title: s.ui === 'supplied' ? 'Mount the Callx call overlay' : 'Connect your call screens', detail: s.ui === 'supplied' ? 'Mount one overlay above app navigation, configure branding and provide controls/video views. Keep Home mounted until incoming acceptance.' : 'Render native snapshots in your own UI and invoke typed commands. Coordinate foreground incoming presentation with the native presenter.', check: s.ui === 'supplied' ? 'Answer opens the same call; Back minimizes presentation without ending it. Native system integration remains enabled.' : 'Navigation follows the same native call ID and app controls use commands. Native system integration remains enabled.', link: '/guide/call-ui'});
  steps.push({title: 'Verify the first call and failure paths', detail: 'Test Answer, Decline, remote end, expiry, duplicate pushes, background and recovery. Then verify video, camera pause and supported PiP behavior.', check: 'Record results on the exact OS/build. Emulator success does not replace physical-device or iOS acceptance.', link: '/guides/testing'});
  return {blockers, steps: blockers.length ? [] : steps, commands: blockers.length ? [] : [install, ...(s.media === 'livekit' ? [adapter] : [])]};
}
